name: Add Google Tag to HTML

on:
  push:
    paths:
      - '**/*.html'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  add-gtag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add Google Tag to HTML files
        run: |
          GTAG='<!-- Google tag (gtag.js) -->
          <script async src="https://www.googletagmanager.com/gtag/js?id=G-V9DHVKBD85"></script>
          <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag("js", new Date());

            gtag("config", "G-V9DHVKBD85");
          </script>'
          for file in $(find . -type f -name "*.html"); do
            if ! grep -q 'googletagmanager.com/gtag/js?id=G-V9DHVKBD85' "$file"; then
              awk -v gtag="$GTAG" '
              BEGIN {added=0}
              /<\/head>/ && !added {
                print gtag
                added=1
              }
              {print}
              ' "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
            fi
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: add Google gtag.js snippet to HTML files"
          file_pattern: .
